exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/ambv/black
    rev: 18.4a4
    hooks:
    - id: black
      args: [--safe, --quiet]
      python_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
        exclude: _pytest/debugging.py
