version: '3'
services:
  selenium:
    image: "selenium/standalone-firefox:3.12.0-cobalt"
    volumes:
    - /dev/shm:/dev/shm
    ports:
     - "4444:4444"
  airtable:
    build: .
    depends_on:
      - "selenium"
    environment:
    - AIRTABLE_USER=buckley.w.david@gmail.com
    - AIRTABLE_PASSWORD=##########
    - APP_ID=##########
    - REMOTE_DRIVER_HOST=http://driver:4444/wd/hub
    links:
      - "selenium:driver"
